export const CONFIG = {
    fonts: ["EurostileBold", "NeueAachenBlack", "HudsonNYSemiBold", "EvanstonTavern1846Regular", "NovecentoBold"],
    presets: [
        "default",
        "BULLS_DUCKS",
        "BULLS_INDIANS",
        "BULLS_BATS",
        "BANDIDOS_INDIANS-II",
        "BULLS_WANDERERS",
        "BULLETS_CARDINALS-II",
        "BULLETS_INDIANS-III",
    ],
    logos: [
        "logo_bb.png",
        "logo_dd.png",
        "logo_di.png",
        "logo_fc.png",
        "logo_gh.png",
        "logo_hb.png",
        "logo_kv.png",
        "logo_st.png",
        "logo_vm.png",
        "logo_vw.png",
    ],
}
